services:
  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/storage
      - ./db/chroma_langchain_db:/db/chroma_langchain_db  # Ensure this matches the persist_directory in the script

  ollama:
    image: ollama/ollama
    ports:
      - "8080:8080"
      
volumes:
  chroma_data: